# Generated by Django 4.2.4 on 2023-08-10 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(default=uuid.UUID('622b9f37-bda3-45bf-b79d-0b90f3ab7148'), editable=False, max_length=36, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_count', models.IntegerField()),
            ],
        ),
    ]
